---
title: "lgrExtra"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lgrExtra}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Development status

lgrExtra uses the the livecycle stages suggested 

https://lifecycle.r-lib.org/articles/lifecycle.html

ApenderDbi | Expiermental



```{r setup}
library(lgr)
library(lgrExtra)
library(RSQLite)


lo <- LayoutDbi$new(
  serialized_cols = list(fields = SerializerJson$new()),
  col_types = c(
    level = "INTEGER",
    timestamp = "TEXT",
    logger= "TEXT",
    msg = "TEXT",
    caller = "TEXT",
    foo = "TEXT",
    fields = "TEXT"
  )
)


ap <- lgrExtra::AppenderDbi$new(
  conn = DBI::dbConnect(RSQLite::SQLite(), 'log.db'),
  table = "log",
  layout = lo,

)

lg <- get_logger("test")$add_appender(ap)
  
lg$info("test", foo = "bar", hash = "baz")  

x <- DBI::dbGetQuery(ap$conn, "select * from log")
x  


```

